import type {
  UiColors,
  UiDecor,
  UiFrame,
  UiGeometry,
  UiScheme,
  UiTheme,
  UiThemeMode,
  UiTypeAxis,
  UiVariants,
} from "#shared/utils/ui-theme";
import { DEFAULT_UI_SCHEME } from "#shared/utils/ui-theme";

/**
 * Зеркало 14 пресетов из утверждённого макета `1e.макеты-14-пресетов.html`
 * (папка планов, `PRESETS`) — то же самое, что панель предлагает оператору
 * в редакторе шаблона (6a). `/ui/?preset=<key>` подставляет один из них
 * поверх темы из базы, ничего не записывая. Мокап называет оси и токены
 * короче настоящей формы (`v.rating`, `footer-alt`, булев `sidebar`) — здесь
 * они разложены по `UiTheme` один в один, включая переименование двух
 * токенов схемы (`footer-alt` → `footer-bg-alt`, `table-border` →
 * `table-row-border`) и превращение булева `sidebar`/`sticky` в реальный
 * enum (`true` → `toc-offer`, потому что во всех пресетах с сайдбаром мокап
 * рисует и оглавление, и карточку оффера вместе).
 */

const LIGHT_SCHEME_BASE: Partial<UiScheme> = {
  "page-bg": "primary-100",
  "header-bg": "primary-100",
  "card-bg": "primary-100",
  "card-border": "primary-300",
  "panel-bg": "primary-200",
  "panel-border": "primary-300",
  "table-row": "primary-100",
  "table-row-alt": "primary-200",
  "table-row-border": "primary-300",
  "input-bg": "primary-100",
  "footer-bg": "accent-300",
  "footer-bg-alt": "accent-200",
};

interface RawPreset {
  key: string;
  name: string;
  mode: UiThemeMode;
  font: {
    display: string;
    body: string;
    weight: number;
    tracking?: string;
    upper?: boolean;
  };
  radius: string;
  colors: UiColors;
  scheme: Partial<UiScheme>;
  scale: NonNullable<UiTypeAxis["scale"]>;
  h1: NonNullable<UiTypeAxis["h1Align"]>;
  density: NonNullable<UiGeometry["density"]>;
  borders: NonNullable<UiGeometry["borders"]>;
  shadow: NonNullable<UiGeometry["shadow"]>;
  header: NonNullable<UiFrame["header"]>;
  headerInverted?: boolean;
  hero: NonNullable<UiFrame["hero"]>;
  heroStyle?: NonNullable<UiFrame["heroStyle"]>;
  sidebar: boolean;
  bands: boolean;
  width: NonNullable<UiFrame["width"]>;
  sticky: NonNullable<UiFrame["sticky"]>;
  h2: NonNullable<UiDecor["h2"]>;
  bg: NonNullable<UiDecor["bg"]>;
  img: NonNullable<UiDecor["img"]>;
  btn: NonNullable<UiDecor["btn"]>;
  variants: {
    breadcrumbs: string;
    ratingStrip: string;
    bonusBox: string;
    toc: string;
    gridCards: string;
    dataTable: string;
    prosCons: string;
    faq: string;
    verdictBox: string;
    biography: string;
    footer: string;
  };
}

const RAW_PRESETS: RawPreset[] = [
  {
    key: "black-gold",
    name: "Black & Gold",
    mode: "dark",
    font: { display: "Playfair Display", body: "Inter", weight: 700 },
    radius: "10px",
    colors: {
      primary: { 300: "#0c0d10", 200: "#15171c", 100: "#212430" },
      active: { 300: "#b58a1f", 200: "#dcae35", 100: "#f3d27a" },
      accent: { 300: "#cdb56a", 200: "#e8d59a", 100: "#f6ecc8" },
    },
    scheme: {
      "card-bg": "primary-200",
      "card-border": "primary-100",
      heading: "accent-100",
      "card-title": "accent-100",
      "table-head-bg": "primary-100",
      "panel-border": "primary-100",
      "badge-bg": "active-200",
      marker: "active-200",
    },
    scale: "display",
    h1: "left",
    density: "airy",
    borders: 1,
    shadow: "none",
    header: "two-row",
    hero: "band",
    heroStyle: "radial",
    sidebar: false,
    bands: false,
    width: "narrow",
    sticky: "bar",
    h2: "underline",
    bg: "radial",
    img: "framed",
    btn: [],
    variants: {
      breadcrumbs: "slash",
      ratingStrip: "scorecard",
      bonusBox: "ticket",
      toc: "box",
      gridCards: "offer",
      dataTable: "ranking",
      prosCons: "two-col",
      faq: "numbered",
      verdictBox: "quote",
      biography: "card",
      footer: "disclaimer",
    },
  },
  {
    key: "neon-violet",
    name: "Neon Violet",
    mode: "dark",
    font: { display: "Unbounded", body: "Manrope", weight: 800 },
    radius: "16px",
    colors: {
      primary: { 300: "#0e0a24", 200: "#181239", 100: "#241b55" },
      active: { 300: "#b31b8f", 200: "#ec2fc0", 100: "#ff8ae4" },
      accent: { 300: "#3b8bff", 200: "#6fb0ff", 100: "#b7d8ff" },
    },
    scheme: {
      heading: "#ffffff",
      "card-title": "#ffffff",
      link: "accent-200",
      "link-hover": "accent-100",
      "card-border": "primary-100",
      "panel-border": "primary-100",
      "table-head-bg": "primary-100",
      "cta-bg": "active-300",
      "cta-hover": "active-200",
      "cta-text": "#ffffff",
      marker: "accent-200",
      "badge-bg": "accent-200",
      "badge-text": "#0e0a24",
    },
    scale: "display",
    h1: "left",
    density: "regular",
    borders: 0,
    shadow: "glow",
    header: "classic",
    hero: "photo",
    heroStyle: "blobs",
    sidebar: false,
    bands: true,
    width: "wide",
    sticky: "button",
    h2: "gradient",
    bg: "flat",
    img: "rounded",
    btn: ["pill", "gradient"],
    variants: {
      breadcrumbs: "pills",
      ratingStrip: "chips",
      bonusBox: "banner",
      toc: "pills",
      gridCards: "image-title-text",
      dataTable: "rows",
      prosCons: "scoreboard",
      faq: "chat",
      verdictBox: "split",
      biography: "inline",
      footer: "centered",
    },
  },
  {
    key: "acid-charcoal",
    name: "Acid Charcoal",
    mode: "dark",
    font: {
      display: "Bebas Neue",
      body: "Barlow",
      weight: 400,
      tracking: ".03em",
      upper: true,
    },
    radius: "3px",
    colors: {
      primary: { 300: "#111315", 200: "#1a1d21", 100: "#25292f" },
      active: { 300: "#b8cc12", 200: "#e2ff2e", 100: "#f1ff8a" },
      accent: { 300: "#c9ced6", 200: "#e8ebef", 100: "#ffffff" },
    },
    scheme: {
      heading: "#ffffff",
      "card-title": "active-200",
      link: "active-200",
      "link-hover": "active-100",
      "card-bg": "primary-200",
      "card-border": "primary-100",
      "panel-border": "primary-100",
      "table-head-bg": "active-200",
      "table-head-text": "#111315",
      marker: "active-200",
      "badge-bg": "active-200",
    },
    scale: "regular",
    h1: "left",
    density: "tight",
    borders: 2,
    shadow: "none",
    header: "compact",
    hero: "band",
    heroStyle: "skew",
    sidebar: false,
    bands: false,
    width: "wide",
    sticky: "bar",
    h2: "left-rule",
    bg: "stripes",
    img: "square",
    btn: ["skew"],
    variants: {
      breadcrumbs: "back",
      ratingStrip: "bars",
      bonusBox: "split",
      toc: "rule",
      gridCards: "horizontal",
      dataTable: "classic",
      prosCons: "table",
      faq: "list",
      verdictBox: "strip",
      biography: "signature",
      footer: "minimal",
    },
  },
  {
    key: "navy-mint",
    name: "Navy Mint",
    mode: "dark",
    font: { display: "Sora", body: "Inter", weight: 800 },
    radius: "12px",
    colors: {
      primary: { 300: "#0a1020", 200: "#111a30", 100: "#1a2746" },
      active: { 300: "#159a5c", 200: "#22c55e", 100: "#86efac" },
      accent: { 300: "#2563eb", 200: "#3b82f6", 100: "#93c5fd" },
    },
    scheme: {
      heading: "#ffffff",
      "card-title": "#ffffff",
      link: "accent-100",
      "link-hover": "accent-200",
      "card-bg": "primary-200",
      "card-border": "primary-100",
      "panel-border": "primary-100",
      "table-head-bg": "accent-300",
      "table-head-text": "#ffffff",
      marker: "accent-200",
      "badge-bg": "active-200",
      "badge-text": "#0a1020",
      "cta-text": "#06130a",
    },
    scale: "compact",
    h1: "left",
    density: "regular",
    borders: 1,
    shadow: "none",
    header: "search",
    hero: "none",
    sidebar: true,
    bands: false,
    width: "wide",
    sticky: "bar",
    h2: "none",
    bg: "flat",
    img: "rounded",
    btn: [],
    variants: {
      breadcrumbs: "slash",
      ratingStrip: "strip",
      bonusBox: "stripe",
      toc: "columns",
      gridCards: "offer",
      dataTable: "compare",
      prosCons: "two-col",
      faq: "grid",
      verdictBox: "card",
      biography: "card",
      footer: "columns",
    },
  },
  {
    key: "ember",
    name: "Ember",
    mode: "dark",
    font: { display: "Russo One", body: "Rubik", weight: 400 },
    radius: "10px",
    colors: {
      primary: { 300: "#120a09", 200: "#1d100e", 100: "#2c1815" },
      active: { 300: "#c8381a", 200: "#ff5a1f", 100: "#ff9a6b" },
      accent: { 300: "#d9a21b", 200: "#ffc531", 100: "#ffe08a" },
    },
    scheme: {
      heading: "accent-200",
      "card-title": "accent-200",
      link: "active-100",
      "link-hover": "accent-200",
      "card-bg": "primary-200",
      "card-border": "primary-100",
      "panel-border": "primary-100",
      "table-head-bg": "primary-100",
      "cta-text": "#1a0d08",
      marker: "accent-200",
      "badge-bg": "accent-200",
    },
    scale: "display",
    h1: "center",
    density: "regular",
    borders: 1,
    shadow: "soft",
    header: "centered",
    hero: "band",
    heroStyle: "warm",
    sidebar: false,
    bands: true,
    width: "wide",
    sticky: "button",
    h2: "dot",
    bg: "flat",
    img: "tilt",
    btn: ["gradient"],
    variants: {
      breadcrumbs: "slash",
      ratingStrip: "scorecard",
      bonusBox: "banner",
      toc: "steps",
      gridCards: "image-caption",
      dataTable: "rows",
      prosCons: "merged",
      faq: "accordion",
      verdictBox: "split",
      biography: "banner",
      footer: "disclaimer",
    },
  },
  {
    key: "mint-black",
    name: "Mint Black",
    mode: "dark",
    font: { display: "Manrope", body: "Manrope", weight: 800 },
    radius: "18px",
    colors: {
      primary: { 300: "#0f1113", 200: "#171a1d", 100: "#22262b" },
      active: { 300: "#2bbf86", 200: "#5cf2b0", 100: "#b6ffdd" },
      accent: { 300: "#8b93a1", 200: "#c3c9d3", 100: "#ffffff" },
    },
    scheme: {
      heading: "#ffffff",
      "card-title": "#ffffff",
      link: "active-200",
      "link-hover": "active-100",
      "card-bg": "primary-200",
      "card-border": "primary-200",
      "panel-border": "primary-200",
      "table-head-bg": "primary-100",
      marker: "active-200",
      "badge-bg": "active-200",
    },
    scale: "regular",
    h1: "left",
    density: "airy",
    borders: 0,
    shadow: "soft",
    header: "compact",
    hero: "none",
    sidebar: false,
    bands: false,
    width: "narrow",
    sticky: "bar",
    h2: "none",
    bg: "flat",
    img: "rounded",
    btn: ["pill"],
    variants: {
      breadcrumbs: "back",
      ratingStrip: "chips",
      bonusBox: "bar",
      toc: "pills",
      gridCards: "image-title-text",
      dataTable: "key-value",
      prosCons: "stacked",
      faq: "accordion",
      verdictBox: "card",
      biography: "inline",
      footer: "minimal",
    },
  },
  {
    key: "emerald-felt",
    name: "Emerald Felt",
    mode: "dark",
    font: {
      display: "Cinzel",
      body: "Lora",
      weight: 700,
      tracking: ".02em",
    },
    radius: "6px",
    colors: {
      primary: { 300: "#0b2419", 200: "#113324", 100: "#1a4632" },
      active: { 300: "#b8901f", 200: "#dfb43a", 100: "#f4d77c" },
      accent: { 300: "#d9c9a0", 200: "#efe3c2", 100: "#f9f3e3" },
    },
    scheme: {
      heading: "accent-200",
      "card-title": "accent-200",
      "card-bg": "primary-200",
      "card-border": "primary-100",
      "panel-border": "primary-100",
      "table-head-bg": "primary-100",
      marker: "active-200",
      "badge-bg": "active-200",
    },
    scale: "regular",
    h1: "center",
    density: "regular",
    borders: 1,
    shadow: "none",
    header: "two-row",
    hero: "band",
    heroStyle: "radial",
    sidebar: false,
    bands: false,
    width: "narrow",
    sticky: "button",
    h2: "number",
    bg: "dots",
    img: "framed",
    btn: [],
    variants: {
      breadcrumbs: "slash",
      ratingStrip: "strip",
      bonusBox: "banner",
      toc: "box",
      gridCards: "text",
      dataTable: "classic",
      prosCons: "two-col",
      faq: "list",
      verdictBox: "card",
      biography: "centered",
      footer: "disclaimer",
    },
  },
  {
    key: "guru-red",
    name: "Guru Red",
    mode: "light",
    font: { display: "Archivo", body: "Roboto", weight: 900 },
    radius: "6px",
    colors: {
      primary: { 300: "#e4e4e7", 200: "#f4f4f5", 100: "#ffffff" },
      active: { 300: "#b71c2e", 200: "#d7263d", 100: "#f0a3ad" },
      accent: { 300: "#18181b", 200: "#27272a", 100: "#71717a" },
    },
    scheme: {
      ...LIGHT_SCHEME_BASE,
      heading: "accent-300",
      "card-title": "accent-300",
      link: "active-300",
      "link-hover": "accent-300",
      "cta-bg": "active-200",
      "cta-hover": "active-300",
      "cta-text": "#ffffff",
      "table-head-bg": "accent-300",
      "table-head-text": "#ffffff",
      "badge-bg": "active-200",
      "badge-text": "#ffffff",
      marker: "active-200",
    },
    scale: "regular",
    h1: "left",
    density: "tight",
    borders: 1,
    shadow: "none",
    header: "classic",
    headerInverted: false,
    hero: "none",
    sidebar: false,
    bands: false,
    width: "wide",
    sticky: "bar",
    h2: "left-rule",
    bg: "flat",
    img: "rounded",
    btn: [],
    variants: {
      breadcrumbs: "slash",
      ratingStrip: "strip",
      bonusBox: "stripe",
      toc: "box",
      gridCards: "offer",
      dataTable: "ranking",
      prosCons: "two-col",
      faq: "accordion",
      verdictBox: "card",
      biography: "inline",
      footer: "columns",
    },
  },
  {
    key: "indigo-fintech",
    name: "Indigo Fintech",
    mode: "light",
    font: { display: "Plus Jakarta Sans", body: "Inter", weight: 800 },
    radius: "14px",
    colors: {
      primary: { 300: "#e2e8f0", 200: "#f1f5f9", 100: "#ffffff" },
      active: { 300: "#4338ca", 200: "#4f46e5", 100: "#a5b4fc" },
      accent: { 300: "#0f172a", 200: "#1e293b", 100: "#64748b" },
    },
    scheme: {
      ...LIGHT_SCHEME_BASE,
      heading: "accent-300",
      "card-title": "accent-300",
      link: "active-300",
      "link-hover": "accent-300",
      "cta-bg": "active-200",
      "cta-hover": "active-300",
      "cta-text": "#ffffff",
      "table-head-bg": "primary-200",
      "table-head-text": "accent-300",
      "badge-bg": "active-200",
      "badge-text": "#ffffff",
      marker: "active-200",
    },
    scale: "regular",
    h1: "left",
    density: "airy",
    borders: 0,
    shadow: "soft",
    header: "search",
    headerInverted: false,
    hero: "band",
    heroStyle: "pale",
    sidebar: true,
    bands: false,
    width: "wide",
    sticky: "bar",
    h2: "none",
    bg: "flat",
    img: "rounded",
    btn: ["pill"],
    variants: {
      breadcrumbs: "pills",
      ratingStrip: "scorecard",
      bonusBox: "split",
      toc: "columns",
      gridCards: "image-title-text",
      dataTable: "compare",
      prosCons: "scoreboard",
      faq: "accordion",
      verdictBox: "split",
      biography: "card",
      footer: "columns",
    },
  },
  {
    key: "cream-gold",
    name: "Cream Gold",
    mode: "light",
    font: { display: "Playfair Display", body: "Source Sans 3", weight: 700 },
    radius: "8px",
    colors: {
      primary: { 300: "#e9dfc7", 200: "#f3ecdb", 100: "#faf6ec" },
      active: { 300: "#8a6a12", 200: "#b8891c", 100: "#e3c26a" },
      accent: { 300: "#2b1d0e", 200: "#4a3418", 100: "#8c7a5b" },
    },
    scheme: {
      ...LIGHT_SCHEME_BASE,
      heading: "accent-300",
      "card-title": "accent-300",
      link: "active-300",
      "link-hover": "accent-300",
      "cta-bg": "active-300",
      "cta-hover": "active-200",
      "cta-text": "#ffffff",
      "table-head-bg": "accent-300",
      "table-head-text": "#faf6ec",
      "badge-bg": "active-300",
      "badge-text": "#ffffff",
      marker: "active-200",
    },
    scale: "display",
    h1: "center",
    density: "airy",
    borders: 1,
    shadow: "none",
    header: "two-row",
    headerInverted: false,
    hero: "photo",
    heroStyle: "radial",
    sidebar: false,
    bands: false,
    width: "narrow",
    sticky: "none",
    h2: "underline",
    bg: "flat",
    img: "framed",
    btn: [],
    variants: {
      breadcrumbs: "slash",
      ratingStrip: "scorecard",
      bonusBox: "ticket",
      toc: "rule",
      gridCards: "text",
      dataTable: "ranking",
      prosCons: "two-col",
      faq: "numbered",
      verdictBox: "quote",
      biography: "banner",
      footer: "disclaimer",
    },
  },
  {
    key: "sport-light",
    name: "Sport Light",
    mode: "light",
    font: {
      display: "Oswald",
      body: "Barlow",
      weight: 700,
      upper: true,
      tracking: ".02em",
    },
    radius: "3px",
    colors: {
      primary: { 300: "#dbe4f3", 200: "#eef2f9", 100: "#ffffff" },
      active: { 300: "#d4a90a", 200: "#facc15", 100: "#fde68a" },
      accent: { 300: "#1e3a8a", 200: "#1d4ed8", 100: "#93c5fd" },
    },
    scheme: {
      ...LIGHT_SCHEME_BASE,
      "header-bg": "accent-300",
      heading: "accent-300",
      "card-title": "accent-200",
      link: "accent-200",
      "link-hover": "accent-300",
      "cta-bg": "active-200",
      "cta-hover": "active-300",
      "cta-text": "#111111",
      "table-head-bg": "accent-200",
      "table-head-text": "#ffffff",
      "badge-bg": "accent-200",
      "badge-text": "#ffffff",
      marker: "accent-200",
    },
    scale: "display",
    h1: "left",
    density: "tight",
    borders: 2,
    shadow: "none",
    header: "compact",
    headerInverted: true,
    hero: "band",
    heroStyle: "solid",
    sidebar: false,
    bands: false,
    width: "wide",
    sticky: "button",
    h2: "left-rule",
    bg: "stripes",
    img: "square",
    btn: ["skew"],
    variants: {
      breadcrumbs: "back",
      ratingStrip: "bars",
      bonusBox: "split",
      toc: "pills",
      gridCards: "horizontal",
      dataTable: "classic",
      prosCons: "table",
      faq: "list",
      verdictBox: "strip",
      biography: "signature",
      footer: "minimal",
    },
  },
  {
    key: "teal-pay",
    name: "Teal Pay",
    mode: "light",
    font: { display: "Sora", body: "Inter", weight: 800 },
    radius: "12px",
    colors: {
      primary: { 300: "#d9e2e1", 200: "#eef3f2", 100: "#ffffff" },
      active: { 300: "#0f766e", 200: "#0d9488", 100: "#5eead4" },
      accent: { 300: "#0f172a", 200: "#334155", 100: "#64748b" },
    },
    scheme: {
      ...LIGHT_SCHEME_BASE,
      heading: "accent-300",
      "card-title": "accent-300",
      link: "active-300",
      "link-hover": "accent-300",
      "cta-bg": "active-300",
      "cta-hover": "active-200",
      "cta-text": "#ffffff",
      "table-head-bg": "accent-300",
      "table-head-text": "#ffffff",
      "badge-bg": "active-300",
      "badge-text": "#ffffff",
      marker: "active-200",
    },
    scale: "compact",
    h1: "left",
    density: "regular",
    borders: 1,
    shadow: "none",
    header: "classic",
    headerInverted: false,
    hero: "none",
    sidebar: true,
    bands: false,
    width: "wide",
    sticky: "bar",
    h2: "none",
    bg: "dots",
    img: "rounded",
    btn: [],
    variants: {
      breadcrumbs: "slash",
      ratingStrip: "chips",
      bonusBox: "stripe",
      toc: "columns",
      gridCards: "offer",
      dataTable: "key-value",
      prosCons: "stacked",
      faq: "grid",
      verdictBox: "card",
      biography: "card",
      footer: "columns",
    },
  },
  {
    key: "lilac-play",
    name: "Lilac Play",
    mode: "light",
    font: { display: "Fredoka", body: "Nunito", weight: 700 },
    radius: "22px",
    colors: {
      primary: { 300: "#e4dcff", 200: "#f1ecff", 100: "#faf8ff" },
      active: { 300: "#6d28d9", 200: "#7c3aed", 100: "#c4b5fd" },
      accent: { 300: "#be185d", 200: "#ec4899", 100: "#f9a8d4" },
    },
    scheme: {
      ...LIGHT_SCHEME_BASE,
      "card-bg": "#ffffff",
      "table-row": "#ffffff",
      "input-bg": "#ffffff",
      heading: "active-300",
      "card-title": "active-300",
      link: "active-300",
      "link-hover": "accent-300",
      "cta-bg": "active-300",
      "cta-hover": "active-200",
      "cta-text": "#ffffff",
      "table-head-bg": "primary-300",
      "table-head-text": "active-300",
      "badge-bg": "accent-300",
      "badge-text": "#ffffff",
      marker: "accent-200",
      "footer-bg": "active-300",
      "footer-bg-alt": "active-200",
    },
    scale: "display",
    h1: "center",
    density: "airy",
    borders: 0,
    shadow: "soft",
    header: "centered",
    headerInverted: false,
    hero: "band",
    heroStyle: "blobs",
    sidebar: false,
    bands: true,
    width: "narrow",
    sticky: "button",
    h2: "dot",
    bg: "flat",
    img: "rounded",
    btn: ["pill", "gradient"],
    variants: {
      breadcrumbs: "pills",
      ratingStrip: "chips",
      bonusBox: "banner",
      toc: "steps",
      gridCards: "image-caption",
      dataTable: "rows",
      prosCons: "merged",
      faq: "chat",
      verdictBox: "split",
      biography: "centered",
      footer: "centered",
    },
  },
  {
    key: "paper-news",
    name: "Paper News",
    mode: "light",
    font: { display: "DM Serif Display", body: "DM Sans", weight: 400 },
    radius: "0px",
    colors: {
      primary: { 300: "#dcdcdc", 200: "#ececec", 100: "#f5f5f4" },
      active: { 300: "#c2410c", 200: "#ea580c", 100: "#fdba74" },
      accent: { 300: "#111111", 200: "#262626", 100: "#525252" },
    },
    scheme: {
      ...LIGHT_SCHEME_BASE,
      "header-bg": "accent-300",
      "card-bg": "#ffffff",
      "table-row": "#ffffff",
      "input-bg": "#ffffff",
      heading: "accent-300",
      "card-title": "accent-300",
      link: "active-300",
      "link-hover": "accent-300",
      "cta-bg": "accent-300",
      "cta-hover": "accent-200",
      "cta-text": "#ffffff",
      "table-head-bg": "accent-300",
      "table-head-text": "#ffffff",
      "badge-bg": "active-300",
      "badge-text": "#ffffff",
      marker: "active-200",
    },
    scale: "regular",
    h1: "left",
    density: "regular",
    borders: 1,
    shadow: "none",
    header: "classic",
    headerInverted: true,
    hero: "none",
    sidebar: false,
    bands: false,
    width: "narrow",
    sticky: "none",
    h2: "line",
    bg: "flat",
    img: "square",
    btn: [],
    variants: {
      breadcrumbs: "slash",
      ratingStrip: "bars",
      bonusBox: "stripe",
      toc: "box",
      gridCards: "text",
      dataTable: "ranking",
      prosCons: "two-col",
      faq: "numbered",
      verdictBox: "quote",
      biography: "card",
      footer: "columns",
    },
  },
];

const PRESET_UPDATED_AT = new Date("2026-09-16T00:00:00.000Z");

const buildPreset = (raw: RawPreset): UiTheme => ({
  templateId: raw.key,
  templateName: raw.name,
  mode: raw.mode,
  colors: raw.colors,
  scheme: { ...DEFAULT_UI_SCHEME, ...raw.scheme },
  type: {
    display: {
      family: raw.font.display,
      weight: raw.font.weight,
      ...(raw.font.upper ? { case: "upper" as const } : {}),
      ...(raw.font.tracking ? { tracking: raw.font.tracking } : {}),
    },
    body: { family: raw.font.body },
    scale: raw.scale,
    h1Align: raw.h1,
  },
  geometry: {
    radius: raw.radius,
    borders: raw.borders,
    shadow: raw.shadow,
    density: raw.density,
  },
  frame: {
    header: raw.header,
    ...(raw.headerInverted !== undefined
      ? { headerInverted: raw.headerInverted }
      : {}),
    hero: raw.hero,
    ...(raw.heroStyle ? { heroStyle: raw.heroStyle } : {}),
    sidebar: raw.sidebar ? "toc-offer" : "none",
    bands: raw.bands,
    width: raw.width,
    sticky: raw.sticky,
  },
  variants: raw.variants,
  decor: {
    h2: raw.h2,
    bg: raw.bg,
    img: raw.img,
    btn: raw.btn,
  },
  accents: {},
  updatedAt: PRESET_UPDATED_AT,
});

// 14 готовых тем — 7 тёмных и 7 светлых, тот же порядок, что в макете.
export const UI_PRESETS: UiTheme[] = RAW_PRESETS.map(buildPreset);

export const findUiPreset = (templateId: string): UiTheme | null =>
  UI_PRESETS.find((preset) => preset.templateId === templateId) || null;
